-- Initial Django schema and seed data; apply only to an empty D1.
CREATE TABLE "account_emailaddress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "verified" bool NOT NULL, "primary" bool NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "email" varchar(254) NOT NULL);
CREATE TABLE "account_emailconfirmation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "sent" datetime NULL, "key" varchar(64) NOT NULL UNIQUE, "email_address_id" integer NOT NULL REFERENCES "account_emailaddress" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "polls_approveddiscorduser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "discord_id" varchar(20) NOT NULL UNIQUE, "enabled" bool NOT NULL, "note" varchar(100) NOT NULL);
CREATE TABLE "polls_ballot" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "voter_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "poll_week_id" bigint NOT NULL REFERENCES "polls_pollweek" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "unique_weekly_ballot" UNIQUE ("poll_week_id", "voter_id"));
CREATE TABLE "polls_pollweek" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "season" integer unsigned NOT NULL CHECK ("season" >= 0), "week" integer unsigned NOT NULL CHECK ("week" >= 0), CONSTRAINT "unique_poll_week" UNIQUE ("season", "week"), CONSTRAINT "poll_season_positive" CHECK ("season" >= 1), CONSTRAINT "poll_week_positive" CHECK ("week" >= 1));
CREATE TABLE "polls_quarterback" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "team_id" bigint NULL REFERENCES "polls_team" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "polls_team" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "abbreviation" varchar(3) NOT NULL UNIQUE);
CREATE TABLE "polls_vote" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "rank" integer unsigned NOT NULL CHECK ("rank" >= 0), "ballot_id" bigint NOT NULL REFERENCES "polls_ballot" ("id") DEFERRABLE INITIALLY DEFERRED, "quarterback_id" bigint NOT NULL REFERENCES "polls_quarterback" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "unique_ballot_rank" UNIQUE ("ballot_id", "rank"), CONSTRAINT "unique_ballot_qb" UNIQUE ("ballot_id", "quarterback_id"), CONSTRAINT "vote_rank_positive" CHECK ("rank" >= 1));
CREATE TABLE "socialaccount_socialaccount" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "provider" varchar(200) NOT NULL, "uid" varchar(191) NOT NULL, "last_login" datetime NOT NULL, "date_joined" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "extra_data" text NOT NULL CHECK ((JSON_VALID("extra_data") OR "extra_data" IS NULL)));
CREATE TABLE "socialaccount_socialapp" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "provider" varchar(30) NOT NULL, "name" varchar(40) NOT NULL, "client_id" varchar(191) NOT NULL, "secret" varchar(191) NOT NULL, "key" varchar(191) NOT NULL, "provider_id" varchar(200) NOT NULL, "settings" text NOT NULL CHECK ((JSON_VALID("settings") OR "settings" IS NULL)));
CREATE TABLE "socialaccount_socialtoken" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "token" text NOT NULL, "token_secret" text NOT NULL, "expires_at" datetime NULL, "account_id" integer NOT NULL REFERENCES "socialaccount_socialaccount" ("id") DEFERRABLE INITIALLY DEFERRED, "app_id" integer NULL REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','group');
INSERT INTO "django_content_type" VALUES(3,'auth','permission');
INSERT INTO "django_content_type" VALUES(4,'auth','user');
INSERT INTO "django_content_type" VALUES(5,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(6,'sessions','session');
INSERT INTO "django_content_type" VALUES(7,'account','emailaddress');
INSERT INTO "django_content_type" VALUES(8,'account','emailconfirmation');
INSERT INTO "django_content_type" VALUES(9,'socialaccount','socialaccount');
INSERT INTO "django_content_type" VALUES(10,'socialaccount','socialapp');
INSERT INTO "django_content_type" VALUES(11,'socialaccount','socialtoken');
INSERT INTO "django_content_type" VALUES(12,'polls','approveddiscorduser');
INSERT INTO "django_content_type" VALUES(13,'polls','ballot');
INSERT INTO "django_content_type" VALUES(14,'polls','pollweek');
INSERT INTO "django_content_type" VALUES(15,'polls','quarterback');
INSERT INTO "django_content_type" VALUES(16,'polls','team');
INSERT INTO "django_content_type" VALUES(17,'polls','vote');
INSERT INTO "django_migrations" VALUES(1,'contenttypes','0001_initial','2026-09-28 19:54:44.460151');
INSERT INTO "django_migrations" VALUES(2,'auth','0001_initial','2026-09-28 19:54:44.467115');
INSERT INTO "django_migrations" VALUES(3,'account','0001_initial','2026-09-28 19:54:44.474155');
INSERT INTO "django_migrations" VALUES(4,'account','0002_email_max_length','2026-09-28 19:54:44.478740');
INSERT INTO "django_migrations" VALUES(5,'account','0003_alter_emailaddress_create_unique_verified_email','2026-09-28 19:54:44.485207');
INSERT INTO "django_migrations" VALUES(6,'account','0004_alter_emailaddress_drop_unique_email','2026-09-28 19:54:44.490164');
INSERT INTO "django_migrations" VALUES(7,'account','0005_emailaddress_idx_upper_email','2026-09-28 19:54:44.493493');
INSERT INTO "django_migrations" VALUES(8,'account','0006_emailaddress_lower','2026-09-28 19:54:44.497513');
INSERT INTO "django_migrations" VALUES(9,'account','0007_emailaddress_idx_email','2026-09-28 19:54:44.505055');
INSERT INTO "django_migrations" VALUES(10,'account','0008_emailaddress_unique_primary_email_fixup','2026-09-28 19:54:44.509456');
INSERT INTO "django_migrations" VALUES(11,'account','0009_emailaddress_unique_primary_email','2026-09-28 19:54:44.512601');
INSERT INTO "django_migrations" VALUES(12,'admin','0001_initial','2026-09-28 19:54:44.516937');
INSERT INTO "django_migrations" VALUES(13,'admin','0002_logentry_remove_auto_add','2026-09-28 19:54:44.521759');
INSERT INTO "django_migrations" VALUES(14,'admin','0003_logentry_add_action_flag_choices','2026-09-28 19:54:44.525352');
INSERT INTO "django_migrations" VALUES(15,'contenttypes','0002_remove_content_type_name','2026-09-28 19:54:44.537319');
INSERT INTO "django_migrations" VALUES(16,'auth','0002_alter_permission_name_max_length','2026-09-28 19:54:44.543059');
INSERT INTO "django_migrations" VALUES(17,'auth','0003_alter_user_email_max_length','2026-09-28 19:54:44.548226');
INSERT INTO "django_migrations" VALUES(18,'auth','0004_alter_user_username_opts','2026-09-28 19:54:44.552251');
INSERT INTO "django_migrations" VALUES(19,'auth','0005_alter_user_last_login_null','2026-09-28 19:54:44.556982');
INSERT INTO "django_migrations" VALUES(20,'auth','0006_require_contenttypes_0002','2026-09-28 19:54:44.557290');
INSERT INTO "django_migrations" VALUES(21,'auth','0007_alter_validators_add_error_messages','2026-09-28 19:54:44.561186');
INSERT INTO "django_migrations" VALUES(22,'auth','0008_alter_user_username_max_length','2026-09-28 19:54:44.566022');
INSERT INTO "django_migrations" VALUES(23,'auth','0009_alter_user_last_name_max_length','2026-09-28 19:54:44.570890');
INSERT INTO "django_migrations" VALUES(24,'auth','0010_alter_group_name_max_length','2026-09-28 19:54:44.575690');
INSERT INTO "django_migrations" VALUES(25,'auth','0011_update_proxy_permissions','2026-09-28 19:54:44.579623');
INSERT INTO "django_migrations" VALUES(26,'auth','0012_alter_user_first_name_max_length','2026-09-28 19:54:44.584657');
INSERT INTO "django_migrations" VALUES(27,'polls','0001_initial','2026-09-28 19:54:44.615988');
INSERT INTO "django_migrations" VALUES(28,'polls','0002_approveddiscorduser','2026-09-28 19:54:44.616915');
INSERT INTO "django_migrations" VALUES(29,'polls','0003_seed_teams_and_quarterbacks','2026-09-28 19:54:44.666854');
INSERT INTO "django_migrations" VALUES(30,'sessions','0001_initial','2026-09-28 19:54:44.668044');
INSERT INTO "django_migrations" VALUES(31,'socialaccount','0001_initial','2026-09-28 19:54:44.691970');
INSERT INTO "django_migrations" VALUES(32,'socialaccount','0002_token_max_lengths','2026-09-28 19:54:44.703560');
INSERT INTO "django_migrations" VALUES(33,'socialaccount','0003_extra_data_default_dict','2026-09-28 19:54:44.708190');
INSERT INTO "django_migrations" VALUES(34,'socialaccount','0004_app_provider_id_settings','2026-09-28 19:54:44.719140');
INSERT INTO "django_migrations" VALUES(35,'socialaccount','0005_socialtoken_nullable_app','2026-09-28 19:54:44.727927');
INSERT INTO "django_migrations" VALUES(36,'socialaccount','0006_alter_socialaccount_extra_data','2026-09-28 19:54:44.734682');
INSERT INTO "polls_team" VALUES(1,'Arizona Cardinals','ARI');
INSERT INTO "polls_team" VALUES(2,'Atlanta Falcons','ATL');
INSERT INTO "polls_team" VALUES(3,'Baltimore Ravens','BAL');
INSERT INTO "polls_team" VALUES(4,'Buffalo Bills','BUF');
INSERT INTO "polls_team" VALUES(5,'Carolina Panthers','CAR');
INSERT INTO "polls_team" VALUES(6,'Chicago Bears','CHI');
INSERT INTO "polls_team" VALUES(7,'Cincinnati Bengals','CIN');
INSERT INTO "polls_team" VALUES(8,'Cleveland Browns','CLE');
INSERT INTO "polls_team" VALUES(9,'Dallas Cowboys','DAL');
INSERT INTO "polls_team" VALUES(10,'Denver Broncos','DEN');
INSERT INTO "polls_team" VALUES(11,'Detroit Lions','DET');
INSERT INTO "polls_team" VALUES(12,'Green Bay Packers','GB');
INSERT INTO "polls_team" VALUES(13,'Houston Texans','HOU');
INSERT INTO "polls_team" VALUES(14,'Indianapolis Colts','IND');
INSERT INTO "polls_team" VALUES(15,'Jacksonville Jaguars','JAX');
INSERT INTO "polls_team" VALUES(16,'Kansas City Chiefs','KC');
INSERT INTO "polls_team" VALUES(17,'Las Vegas Raiders','LV');
INSERT INTO "polls_team" VALUES(18,'Los Angeles Chargers','LAC');
INSERT INTO "polls_team" VALUES(19,'Los Angeles Rams','LAR');
INSERT INTO "polls_team" VALUES(20,'Miami Dolphins','MIA');
INSERT INTO "polls_team" VALUES(21,'Minnesota Vikings','MIN');
INSERT INTO "polls_team" VALUES(22,'New England Patriots','NE');
INSERT INTO "polls_team" VALUES(23,'New Orleans Saints','NO');
INSERT INTO "polls_team" VALUES(24,'New York Giants','NYG');
INSERT INTO "polls_team" VALUES(25,'New York Jets','NYJ');
INSERT INTO "polls_team" VALUES(26,'Philadelphia Eagles','PHI');
INSERT INTO "polls_team" VALUES(27,'Pittsburgh Steelers','PIT');
INSERT INTO "polls_team" VALUES(28,'San Francisco 49ers','SF');
INSERT INTO "polls_team" VALUES(29,'Seattle Seahawks','SEA');
INSERT INTO "polls_team" VALUES(30,'Tampa Bay Buccaneers','TB');
INSERT INTO "polls_team" VALUES(31,'Tennessee Titans','TEN');
INSERT INTO "polls_team" VALUES(32,'Washington Commanders','WAS');
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,3,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,3,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,3,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,2,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,2,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,2,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,2,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(14,4,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(15,4,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(16,4,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(21,6,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(22,6,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(23,6,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(24,6,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(25,7,'add_emailaddress','Can add email address');
INSERT INTO "auth_permission" VALUES(26,7,'change_emailaddress','Can change email address');
INSERT INTO "auth_permission" VALUES(27,7,'delete_emailaddress','Can delete email address');
INSERT INTO "auth_permission" VALUES(28,7,'view_emailaddress','Can view email address');
INSERT INTO "auth_permission" VALUES(29,8,'add_emailconfirmation','Can add email confirmation');
INSERT INTO "auth_permission" VALUES(30,8,'change_emailconfirmation','Can change email confirmation');
INSERT INTO "auth_permission" VALUES(31,8,'delete_emailconfirmation','Can delete email confirmation');
INSERT INTO "auth_permission" VALUES(32,8,'view_emailconfirmation','Can view email confirmation');
INSERT INTO "auth_permission" VALUES(33,9,'add_socialaccount','Can add social account');
INSERT INTO "auth_permission" VALUES(34,9,'change_socialaccount','Can change social account');
INSERT INTO "auth_permission" VALUES(35,9,'delete_socialaccount','Can delete social account');
INSERT INTO "auth_permission" VALUES(36,9,'view_socialaccount','Can view social account');
INSERT INTO "auth_permission" VALUES(37,10,'add_socialapp','Can add social application');
INSERT INTO "auth_permission" VALUES(38,10,'change_socialapp','Can change social application');
INSERT INTO "auth_permission" VALUES(39,10,'delete_socialapp','Can delete social application');
INSERT INTO "auth_permission" VALUES(40,10,'view_socialapp','Can view social application');
INSERT INTO "auth_permission" VALUES(41,11,'add_socialtoken','Can add social application token');
INSERT INTO "auth_permission" VALUES(42,11,'change_socialtoken','Can change social application token');
INSERT INTO "auth_permission" VALUES(43,11,'delete_socialtoken','Can delete social application token');
INSERT INTO "auth_permission" VALUES(44,11,'view_socialtoken','Can view social application token');
INSERT INTO "auth_permission" VALUES(45,16,'add_team','Can add team');
INSERT INTO "auth_permission" VALUES(46,16,'change_team','Can change team');
INSERT INTO "auth_permission" VALUES(47,16,'delete_team','Can delete team');
INSERT INTO "auth_permission" VALUES(48,16,'view_team','Can view team');
INSERT INTO "auth_permission" VALUES(49,14,'add_pollweek','Can add poll week');
INSERT INTO "auth_permission" VALUES(50,14,'change_pollweek','Can change poll week');
INSERT INTO "auth_permission" VALUES(51,14,'delete_pollweek','Can delete poll week');
INSERT INTO "auth_permission" VALUES(52,14,'view_pollweek','Can view poll week');
INSERT INTO "auth_permission" VALUES(53,13,'add_ballot','Can add ballot');
INSERT INTO "auth_permission" VALUES(54,13,'change_ballot','Can change ballot');
INSERT INTO "auth_permission" VALUES(55,13,'delete_ballot','Can delete ballot');
INSERT INTO "auth_permission" VALUES(56,13,'view_ballot','Can view ballot');
INSERT INTO "auth_permission" VALUES(57,15,'add_quarterback','Can add quarterback');
INSERT INTO "auth_permission" VALUES(58,15,'change_quarterback','Can change quarterback');
INSERT INTO "auth_permission" VALUES(59,15,'delete_quarterback','Can delete quarterback');
INSERT INTO "auth_permission" VALUES(60,15,'view_quarterback','Can view quarterback');
INSERT INTO "auth_permission" VALUES(61,17,'add_vote','Can add vote');
INSERT INTO "auth_permission" VALUES(62,17,'change_vote','Can change vote');
INSERT INTO "auth_permission" VALUES(63,17,'delete_vote','Can delete vote');
INSERT INTO "auth_permission" VALUES(64,17,'view_vote','Can view vote');
INSERT INTO "auth_permission" VALUES(65,12,'add_approveddiscorduser','Can add approved discord user');
INSERT INTO "auth_permission" VALUES(66,12,'change_approveddiscorduser','Can change approved discord user');
INSERT INTO "auth_permission" VALUES(67,12,'delete_approveddiscorduser','Can delete approved discord user');
INSERT INTO "auth_permission" VALUES(68,12,'view_approveddiscorduser','Can view approved discord user');
INSERT INTO "polls_quarterback" VALUES(1,'Drew Allar',27);
INSERT INTO "polls_quarterback" VALUES(2,'Josh Allen',4);
INSERT INTO "polls_quarterback" VALUES(3,'Kyle Allen',4);
INSERT INTO "polls_quarterback" VALUES(4,'Tyson Bagent',6);
INSERT INTO "polls_quarterback" VALUES(5,'Carson Beck',1);
INSERT INTO "polls_quarterback" VALUES(6,'Stetson Bennett IV',19);
INSERT INTO "polls_quarterback" VALUES(7,'Jacoby Brissett',1);
INSERT INTO "polls_quarterback" VALUES(8,'Joe Burrow',7);
INSERT INTO "polls_quarterback" VALUES(9,'Brady Cook',20);
INSERT INTO "polls_quarterback" VALUES(10,'Kirk Cousins',17);
INSERT INTO "polls_quarterback" VALUES(11,'Andy Dalton',26);
INSERT INTO "polls_quarterback" VALUES(12,'Jalon Daniels',30);
INSERT INTO "polls_quarterback" VALUES(13,'Jayden Daniels',32);
INSERT INTO "polls_quarterback" VALUES(14,'Sam Darnold',29);
INSERT INTO "polls_quarterback" VALUES(15,'Tommy DeVito',22);
INSERT INTO "polls_quarterback" VALUES(16,'Joshua Dobbs',11);
INSERT INTO "polls_quarterback" VALUES(17,'Sam Ehlinger',10);
INSERT INTO "polls_quarterback" VALUES(18,'Quinn Ewers',15);
INSERT INTO "polls_quarterback" VALUES(19,'Joe Fagnano',3);
INSERT INTO "polls_quarterback" VALUES(20,'Justin Fields',16);
INSERT INTO "polls_quarterback" VALUES(21,'Joe Flacco',7);
INSERT INTO "polls_quarterback" VALUES(22,'Jared Goff',11);
INSERT INTO "polls_quarterback" VALUES(23,'Taylen Green',8);
INSERT INTO "polls_quarterback" VALUES(24,'Jake Haener',24);
INSERT INTO "polls_quarterback" VALUES(25,'Justin Herbert',18);
INSERT INTO "polls_quarterback" VALUES(26,'Will Howard',27);
INSERT INTO "polls_quarterback" VALUES(27,'Sam Howell',9);
INSERT INTO "polls_quarterback" VALUES(28,'Tyler Huntley',3);
INSERT INTO "polls_quarterback" VALUES(29,'Jalen Hurts',26);
INSERT INTO "polls_quarterback" VALUES(30,'Lamar Jackson',3);
INSERT INTO "polls_quarterback" VALUES(31,'Josh Johnson',7);
INSERT INTO "polls_quarterback" VALUES(32,'Daniel Jones',14);
INSERT INTO "polls_quarterback" VALUES(33,'Mac Jones',28);
INSERT INTO "polls_quarterback" VALUES(34,'Athan Kaliakmanis',32);
INSERT INTO "polls_quarterback" VALUES(35,'Case Keenum',6);
INSERT INTO "polls_quarterback" VALUES(36,'Haynes King',5);
INSERT INTO "polls_quarterback" VALUES(37,'Cade Klubnik',25);
INSERT INTO "polls_quarterback" VALUES(38,'Trey Lance',18);
INSERT INTO "polls_quarterback" VALUES(39,'Trevor Lawrence',15);
INSERT INTO "polls_quarterback" VALUES(40,'Riley Leonard',14);
INSERT INTO "polls_quarterback" VALUES(41,'Will Levis',25);
INSERT INTO "polls_quarterback" VALUES(42,'Drew Lock',29);
INSERT INTO "polls_quarterback" VALUES(43,'Jordan Love',12);
INSERT INTO "polls_quarterback" VALUES(44,'Patrick Mahomes',16);
INSERT INTO "polls_quarterback" VALUES(45,'Marcus Mariota',32);
INSERT INTO "polls_quarterback" VALUES(46,'Drake Maye',22);
INSERT INTO "polls_quarterback" VALUES(47,'Baker Mayfield',30);
INSERT INTO "polls_quarterback" VALUES(48,'J.J. McCarthy',24);
INSERT INTO "polls_quarterback" VALUES(49,'Kyle McCord',20);
INSERT INTO "polls_quarterback" VALUES(50,'Tanner McKee',26);
INSERT INTO "polls_quarterback" VALUES(51,'Fernando Mendoza',17);
INSERT INTO "polls_quarterback" VALUES(52,'Davis Mills',13);
INSERT INTO "polls_quarterback" VALUES(53,'Jalen Milroe',29);
INSERT INTO "polls_quarterback" VALUES(54,'Gardner Minshew II',1);
INSERT INTO "polls_quarterback" VALUES(55,'Behren Morton',22);
INSERT INTO "polls_quarterback" VALUES(56,'Miller Moss',6);
INSERT INTO "polls_quarterback" VALUES(57,'Nick Mullens',15);
INSERT INTO "polls_quarterback" VALUES(58,'Kyler Murray',21);
INSERT INTO "polls_quarterback" VALUES(59,'Bo Nix',10);
INSERT INTO "polls_quarterback" VALUES(60,'Garrett Nussmeier',16);
INSERT INTO "polls_quarterback" VALUES(61,'Aidan O''Connell',17);
INSERT INTO "polls_quarterback" VALUES(62,'Cole Payton',26);
INSERT INTO "polls_quarterback" VALUES(63,'Michael Penix Jr.',2);
INSERT INTO "polls_quarterback" VALUES(64,'Kenny Pickett',5);
INSERT INTO "polls_quarterback" VALUES(65,'Dak Prescott',9);
INSERT INTO "polls_quarterback" VALUES(66,'Brock Purdy',28);
INSERT INTO "polls_quarterback" VALUES(67,'Spencer Rattler',23);
INSERT INTO "polls_quarterback" VALUES(68,'Anthony Richardson Sr.',14);
INSERT INTO "polls_quarterback" VALUES(69,'Aaron Rodgers',27);
INSERT INTO "polls_quarterback" VALUES(70,'Kurtis Rourke',28);
INSERT INTO "polls_quarterback" VALUES(71,'Mason Rudolph',27);
INSERT INTO "polls_quarterback" VALUES(72,'Cooper Rush',2);
INSERT INTO "polls_quarterback" VALUES(73,'Shedeur Sanders',8);
INSERT INTO "polls_quarterback" VALUES(74,'Tyler Shough',23);
INSERT INTO "polls_quarterback" VALUES(75,'Ty Simpson',19);
INSERT INTO "polls_quarterback" VALUES(76,'Geno Smith',25);
INSERT INTO "polls_quarterback" VALUES(77,'Matthew Stafford',19);
INSERT INTO "polls_quarterback" VALUES(78,'Jarrett Stidham',10);
INSERT INTO "polls_quarterback" VALUES(79,'Jack Strand',2);
INSERT INTO "polls_quarterback" VALUES(80,'C.J. Stroud',13);
INSERT INTO "polls_quarterback" VALUES(81,'Tua Tagovailoa',2);
INSERT INTO "polls_quarterback" VALUES(82,'Tyrod Taylor',12);
INSERT INTO "polls_quarterback" VALUES(83,'Mitchell Trubisky',31);
INSERT INTO "polls_quarterback" VALUES(84,'DJ Uiagalelei',18);
INSERT INTO "polls_quarterback" VALUES(85,'Cam Ward',31);
INSERT INTO "polls_quarterback" VALUES(86,'Deshaun Watson',8);
INSERT INTO "polls_quarterback" VALUES(87,'Carson Wentz',21);
INSERT INTO "polls_quarterback" VALUES(88,'Caleb Williams',6);
INSERT INTO "polls_quarterback" VALUES(89,'Malik Willis',20);
INSERT INTO "polls_quarterback" VALUES(90,'Zach Wilson',23);
INSERT INTO "polls_quarterback" VALUES(91,'Jameis Winston',24);
INSERT INTO "polls_quarterback" VALUES(92,'Bryce Young',5);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "account_emailconfirmation_email_address_id_5b7f8c58" ON "account_emailconfirmation" ("email_address_id");
CREATE UNIQUE INDEX "account_emailaddress_user_id_email_987c8728_uniq" ON "account_emailaddress" ("user_id", "email");
CREATE UNIQUE INDEX "unique_verified_email" ON "account_emailaddress" ("email") WHERE "verified" = 1;
CREATE INDEX "account_emailaddress_user_id_2c513194" ON "account_emailaddress" ("user_id");
CREATE INDEX "account_emailaddress_email_03be32b2" ON "account_emailaddress" ("email");
CREATE UNIQUE INDEX "unique_primary_email" ON "account_emailaddress" ("user_id", "primary") WHERE "primary" = 1;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "polls_quarterback_team_id_bb3cd9fb" ON "polls_quarterback" ("team_id");
CREATE INDEX "polls_ballot_voter_id_d26d4293" ON "polls_ballot" ("voter_id");
CREATE INDEX "polls_ballot_poll_week_id_599485c7" ON "polls_ballot" ("poll_week_id");
CREATE INDEX "polls_vote_ballot_id_12a97e6c" ON "polls_vote" ("ballot_id");
CREATE INDEX "polls_vote_quarterback_id_4f708ec6" ON "polls_vote" ("quarterback_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE UNIQUE INDEX "socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq" ON "socialaccount_socialtoken" ("app_id", "account_id");
CREATE INDEX "socialaccount_socialtoken_account_id_951f210e" ON "socialaccount_socialtoken" ("account_id");
CREATE INDEX "socialaccount_socialtoken_app_id_636a42d7" ON "socialaccount_socialtoken" ("app_id");
CREATE UNIQUE INDEX "socialaccount_socialaccount_provider_uid_fc810c6e_uniq" ON "socialaccount_socialaccount" ("provider", "uid");
CREATE INDEX "socialaccount_socialaccount_user_id_8146e70c" ON "socialaccount_socialaccount" ("user_id");
