# Generated by Django 6.1.1 on 2026-09-28 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['-season', '-week'],
                'constraints': [models.UniqueConstraint(fields=('season', 'week'), name='unique_poll_week'), models.CheckConstraint(condition=models.Q(('season__gte', 1)), name='poll_season_positive'), models.CheckConstraint(condition=models.Q(('week__gte', 1)), name='poll_week_positive')],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qb_ballots', to=settings.AUTH_USER_MODEL)),
                ('poll_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.pollweek')),
            ],
        ),
        migrations.CreateModel(
            name='Quarterback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterbacks', to='polls.team')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.ballot')),
                ('quarterback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='polls.quarterback')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('poll_week', 'voter'), name='unique_weekly_ballot'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('ballot', 'rank'), name='unique_ballot_rank'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('ballot', 'quarterback'), name='unique_ballot_qb'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='vote_rank_positive'),
        ),
    ]
