# Generated by Django 6.1.1 on 2026-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_seed_teams_and_quarterbacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollweek",
            name="closes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Voting closes at this time (UTC in the API). Leave blank for no deadline.",
                null=True,
            ),
        ),
    ]
